package main;

import java.io.FileNotFoundException;
import java.util.Arrays;

public class Test {
    public static void main(String[] args) throws FileNotFoundException {
        new Test().test();
        //new Test().zzyTest();
    }

    public void zzyTest(){
        BPlusTree tree = new BPlusTree();
        tree.Insert("ad", 1);
        tree.Insert("bd", 2);
        tree.Insert("cd", 2);
        tree.Insert("dd", 2);
        tree.Insert("ab", 2);
        tree.Insert("ac", 2);
        tree.Insert("cd", 2);
        tree.Insert("cf", 2);
        tree.Insert("cr", 2);
        tree.Insert("ee", 2);
        tree.Insert("gg", 2);
        tree.Insert("hh", 2);
        tree.Insert("ll", 2);
        tree.Insert("ua", 1);
        tree.Insert("ue", 1);
        tree.Insert("ub", 1);
        tree.Insert("up", 1);
        tree.Insert("gh", 1);
        tree.Insert("gg", 1);
        tree.Insert("ga", 1);
        tree.Insert("fa", 1);
//        tree.Insert("fb", 1);
//        tree.Insert("fc", 1);
//        tree.Insert("fd", 1);
//        tree.Insert("fe", 1);
//        tree.Insert("ff", 1);
//        tree.Insert("fo", 1);
//        tree.Insert("oo", 1);
//        tree.Insert("oa", 1);
//        tree.Insert("oc", 1);
//        tree.Insert("ob", 1);
//        tree.Insert("op", 1);
//        tree.Insert("ol", 1);
//        tree.Insert("ok", 1);
//        tree.Insert("or", 1);
//        tree.Insert("io", 1);
//        tree.Insert("ia", 1);
//        tree.Insert("ic", 1);
//        tree.Insert("ib", 1);
//        tree.Insert("ip", 1);
//        tree.Insert("il", 1);
//        tree.Insert("ik", 1);
//        tree.Insert("ir", 1);
//        tree.Insert("eo", 1);
//        tree.Insert("ea", 1);
//        tree.Insert("ec", 1);
//        tree.Insert("eb", 1);
//        tree.Insert("ep", 1);
//        tree.Insert("el", 1);
//        tree.Insert("ek", 1);
//        tree.Insert("er", 1);
//        tree.Insert("jo", 1);
//        tree.Insert("ja", 1);
//        tree.Insert("jc", 1);
//        tree.Insert("jb", 1);
//        tree.Insert("jp", 1);
//        tree.Insert("jl", 1);
//        tree.Insert("jk", 1);
//        tree.Insert("jr", 1);
//        tree.Insert("ko", 1);
//        tree.Insert("ka", 1);
//        tree.Insert("kc", 1);
//        tree.Insert("kb", 1);
//        tree.Insert("kp", 1);
//        tree.Insert("kl", 1);
//        tree.Insert("kk", 1);
//        tree.Insert("kr", 1);
//        tree.Insert("ed", 1);
//        tree.Insert("ee", 1);
//        tree.Insert("ef", 10);
//        tree.Insert("eg", 1);
//        tree.Insert("eh", 1);
//        tree.Insert("ei", 1);
//        tree.Insert("ej", 1);
//        tree.Insert("ek", 1);
        System.out.println(tree);
        tree.Remove("ad");
        System.out.println(tree);
        tree.Remove("ac");
        System.out.println(tree);
        tree.Remove("cf");
        System.out.println(tree);
        tree.Remove("bd");
        System.out.println(tree);
        tree.Remove("asdjna");
        System.out.println(tree);
    }

    public void test() throws FileNotFoundException {
        Utils.SplitToNode("1");
        BPlusTree tree = new BPlusTree();
        tree.Insert("ad", 1);
        System.out.println(tree);
        tree.DumpStatistics();
        tree.Insert("bd", 2);
        tree.Insert("cd", 2);
        tree.Insert("dd", 2);
        tree.Insert("aa", 2);
        System.out.println(tree);
        tree.DumpStatistics();
        tree.Insert("ab", 2);
        tree.Insert("ac", 2);
        tree.Insert("cd", 2);
        tree.Insert("cf", 2);
        tree.Insert("cr", 2);
        //tree.Insert("ee", 2);
        System.out.println(tree);
        tree.DumpStatistics();
        tree.Insert("gg", 2);
        tree.Insert("hh", 2);
        tree.Insert("ll", 2);
        System.out.println(tree);
        tree.Insert("ua", 1);
        tree.Insert("ue", 1);
        tree.Insert("ub", 1);
        tree.Insert("up", 1);
        System.out.println("save" + tree.toString());
        System.out.println(tree);
        tree.DumpStatistics();
        tree.Insert("gh", 1);
        tree.Insert("gg", 1);
        tree.Insert("ga", 1);
        tree.Insert("fa", 1);
        tree.Insert("fb", 1);
        tree.Insert("fc", 1);
        tree.Insert("fd", 1);
        tree.Insert("fe", 1);
        tree.Insert("ff", 1);
        tree.Insert("fo", 1);
        System.out.println(tree);
        tree.DumpStatistics();
        tree.Insert("oo", 1);
        tree.Insert("oa", 1);
        tree.Insert("oc", 1);
        tree.Insert("ob", 1);
        tree.Insert("op", 1);
        tree.Insert("ol", 1);
        tree.Insert("ok", 1);
        tree.Insert("or", 1);
        tree.Insert("io", 1);
        tree.Insert("ia", 1);
        tree.Insert("ic", 1);
        tree.Insert("ib", 1);
        tree.Insert("ip", 1);
        tree.Insert("il", 1);
        tree.Insert("ik", 1);
        tree.Insert("ir", 1);
        tree.Insert("eo", 1);
        tree.Insert("ea", 1);
        tree.Insert("ec", 1);
        tree.Insert("eb", 1);
        tree.Insert("ep", 1);
        tree.Insert("el", 1);
        tree.Insert("ek", 1);
        tree.Insert("er", 1);
        tree.Insert("jo", 1);
        tree.Insert("ja", 1);
        tree.Insert("jc", 1);
        tree.Insert("jb", 1);
        tree.Insert("jp", 1);
        tree.Insert("jl", 1);
        tree.Insert("jk", 1);
        tree.Insert("jr", 1);
        String before1 = tree.toString();
        tree.DumpStatistics();
        tree.Insert("ko", 1);
        tree.Insert("ka", 1);
        tree.Insert("kc", 1);
        tree.Insert("kb", 1);
        tree.Insert("kp", 1);
        tree.Insert("kl", 1);
        tree.Insert("kk", 1);
        tree.Insert("kr", 1);
        tree.Insert("ed", 1);
        tree.Insert("ee", 1);
        tree.Insert("ef", 10);
        System.out.println("this is the initial tree");
        System.out.println(tree);

        tree.Insert("eg", 1);
        tree.Insert("eh", 1);
        tree.Insert("ei", 1);
        tree.Insert("ej", 1);
        tree.Insert("ek", 1);
        tree.Insert("cc", 1);
        tree.Insert("cn", 1);
        tree.Insert("cl", 1);
        tree.Insert("cz", 1);
        tree.Insert("ck", 1);
        System.out.println(tree);
        tree.Remove("ad");
        tree.Remove("bd");
        System.out.println(tree);

        tree.Remove("cc");
        System.out.println(tree);
        tree.Remove("cn");
        System.out.println(tree);
        tree.Remove("cl");
        System.out.println(tree);
        tree.Remove("cz");
        System.out.println(tree);
        tree.Remove("ck");
        System.out.println(tree);
        tree.Remove("eg");
        System.out.println(tree);
        tree.Remove("eh");
        System.out.println(tree);
        tree.Remove("ei");
        System.out.println(tree);
        tree.Remove("ej");
        tree.Remove("ek");
       // System.out.println(before2.equals(tree.toString()));
        tree.Remove("ko");
        System.out.println(tree);
        tree.Remove("ka");
        System.out.println(tree);
        tree.Remove("kc");
        System.out.println(tree);
        tree.Remove("kb");
        System.out.println(tree);
        tree.Remove("kp");
        System.out.println(tree);
        tree.Remove("kl");
        System.out.println(tree);
        tree.Remove("kk");
        System.out.println(tree);
        tree.Remove("kr");
        System.out.println(tree);
        tree.Remove("ed");
        System.out.println(tree);
        tree.Remove("ee");
        System.out.println(tree);
        tree.Remove("ef");
        System.out.println(tree);
//        String before2 = tree.toString();
//        tree.DumpStatistics();
//       // System.out.println(before1.equals(tree.toString()));
//        System.out.println(before1);
//        System.out.println(before2);
//        System.out.println(before1.equals(before2));


    }

    void testGet(BPlusTree tree) {
        //for test purpose, these tow value are set to 10 while others are 1
        System.out.println(tree.Search("ka", "kp"));
        System.out.println(tree.Search("ia", "ub"));
    }

}
